name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [node, python]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        if: matrix.language == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Test (Node)
        if: matrix.language == 'node'
        run: |
          if [ -f package.json ]; then
            npm ci || npm install
            npm test --if-present
          else
            echo "No Node project at root."
          fi

      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install & Test (Python)
        if: matrix.language == 'python'
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
            pytest -q || true
          else
            echo "No Python project at root."
          fi